"""
Tests for the ContinuousBatchScheduler.

Tests scheduler admission, queue overflow, timeout watchdog,
and verifies new Prometheus metrics are registered.
"""

import pytest
import asyncio
import time
from dataclasses import dataclass

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from server.continuous_batch_scheduler import ContinuousBatchScheduler, QueueFullError
from server.sequence import Sequence


@dataclass
class MockRequest:
    """Mimics the request object passed by main.py."""
    prompt: str = None
    messages: list = None
    stream: bool = False
    max_tokens: int = 10
    temperature: float = 1.0
    request_id: str = None


class MockInferenceEngine:
    """
    Fake engine that increments tokens_generated by 1 each step.
    Finishes a sequence when tokens_generated >= max_tokens.
    """
    def _generate_batch_step(self, sequences):
        for seq in sequences:
            if seq.past_key_values is None:
                seq.past_key_values = "mock_pkv"
                seq.input_ids = [1, 2, 3]
                seq.attention_mask = [1, 1, 1]
            else:
                seq.input_ids.append(4)
                seq.attention_mask.append(1)

            seq.tokens_generated += 1
            seq.generated_text += " token"
            if seq.tokens_generated >= seq.max_tokens:
                seq.is_finished = True


# ─── Tests ────────────────────────────────────────────────────────────────────


def test_continuous_batcher_admission():
    """All submitted requests complete with the expected token count."""
    async def _run():
        engine = MockInferenceEngine()
        scheduler = ContinuousBatchScheduler(
            engine, max_running=2, max_waiting=4
        )
        await scheduler.start()

        req1 = MockRequest(prompt="a", request_id="r1", max_tokens=3)
        req2 = MockRequest(prompt="b", request_id="r2", max_tokens=3)
        req3 = MockRequest(prompt="c", request_id="r3", max_tokens=3)

        res1, res2, res3 = await asyncio.gather(
            scheduler.submit(req1),
            scheduler.submit(req2),
            scheduler.submit(req3),
        )

        assert res1.tokens_generated == 3
        assert res2.tokens_generated == 3
        assert res3.tokens_generated == 3
        assert len(scheduler.running_sequences) == 0

        await scheduler.stop()

    asyncio.run(_run())


def test_queue_full_error():
    """QueueFullError is raised when the waiting queue overflows."""
    async def _run():
        engine = MockInferenceEngine()
        # max_waiting=1 means the queue can hold exactly 1 item
        scheduler = ContinuousBatchScheduler(
            engine, max_running=1, max_waiting=1
        )
        # Do NOT start the scheduler so nothing drains

        # First submit goes into the queue (size 1)
        task1 = asyncio.create_task(scheduler.submit(
            MockRequest(prompt="1", request_id="r1")
        ))
        await asyncio.sleep(0.01)  # let put_nowait execute

        # Second submit should overflow
        with pytest.raises(QueueFullError):
            await scheduler.submit(MockRequest(prompt="2", request_id="r2"))

        task1.cancel()

    asyncio.run(_run())


def test_sequence_timeout():
    """Sequences exceeding MAX_SEQUENCE_TIMEOUT_S are evicted with TimeoutError."""
    async def _run():
        class SlowEngine(MockInferenceEngine):
            def _generate_batch_step(self, sequences):
                time.sleep(0.15)  # slow enough to trigger 0.2s timeout
                super()._generate_batch_step(sequences)

        scheduler = ContinuousBatchScheduler(
            SlowEngine(), max_running=1, max_waiting=4, max_timeout=0.2
        )
        await scheduler.start()

        req = MockRequest(prompt="slow", request_id="slow1", max_tokens=100)

        with pytest.raises(TimeoutError):
            await scheduler.submit(req)

        await scheduler.stop()

    asyncio.run(_run())


def test_stats_property():
    """The stats dict contains the expected keys."""
    async def _run():
        engine = MockInferenceEngine()
        scheduler = ContinuousBatchScheduler(engine, max_running=4, max_waiting=10)
        stats = scheduler.stats
        assert "running_sequences" in stats
        assert "queue_depth" in stats
        assert "max_running" in stats
        assert stats["max_running"] == 4
        assert stats["max_waiting"] == 10

    asyncio.run(_run())


def test_prometheus_metrics_registered():
    """New Prometheus metrics are importable and registered."""
    from server import metrics as m

    # Verify new metrics exist
    assert hasattr(m, "SCHEDULER_RUNNING_SEQUENCES")
    assert hasattr(m, "SCHEDULER_HEARTBEAT")
    assert hasattr(m, "STEP_LATENCY")

    # Verify they appear in the /metrics output
    output = m.get_metrics().decode()
    assert "miniserve_scheduler_running_sequences" in output
    assert "miniserve_scheduler_heartbeat" in output
    assert "miniserve_step_latency_seconds" in output
