# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"^\n\x0fGenerateRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x12\n\nmax_tokens\x18\x02 \x01(\x05\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\x12\n\nrequest_id\x18\x04 \x01(\t\"\x14\n\x12HealthCheckRequest\"\xbb\x01\n\x10GenerateResponse\x12\x16\n\x0egenerated_text\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12\x18\n\x10tokens_generated\x18\x03 \x01(\x05\x12\x12\n\nlatency_ms\x18\x04 \x01(\x02\x12\x12\n\nbatch_size\x18\x05 \x01(\x05\x12\x15\n\rqueue_wait_ms\x18\x06 \x01(\x02\x12\x12\n\nfrom_cache\x18\x07 \x01(\x08\x12\x12\n\nrequest_id\x18\x08 \x01(\t\"Y\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x65vice\x18\x03 \x01(\t\x12\x13\n\x0bqueue_depth\x18\x04 \x01(\x05\x32\xa5\x01\n\x10InferenceService\x12\x43\n\x08Generate\x12\x1a.inference.GenerateRequest\x1a\x1b.inference.GenerateResponse\x12L\n\x0bHealthCheck\x12\x1d.inference.HealthCheckRequest\x1a\x1e.inference.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEREQUEST']._serialized_start=30
  _globals['_GENERATEREQUEST']._serialized_end=124
  _globals['_HEALTHCHECKREQUEST']._serialized_start=126
  _globals['_HEALTHCHECKREQUEST']._serialized_end=146
  _globals['_GENERATERESPONSE']._serialized_start=149
  _globals['_GENERATERESPONSE']._serialized_end=336
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=338
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=427
  _globals['_INFERENCESERVICE']._serialized_start=430
  _globals['_INFERENCESERVICE']._serialized_end=595
# @@protoc_insertion_point(module_scope)
